-- ============================================================================
-- Seed: dorm hero images (generated by scripts/fetch-dorm-images.mjs)
-- APPLY: psql $DATABASE_URL -f supabase/seeds/dorm_images.sql
-- Idempotent: upserts image_url on slug.
-- ============================================================================

update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-gasgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-kandlgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-molkereistrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-sechshauser-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-simmeringer-hauptstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tigergasse_gallery1.max-1920x1080.jpg' where slug = 'oead-guesthouse-tigergasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/AufDerSchmelz_Gallery-Eingang.max-1920x1080.jpg' where slug = 'oead-apartment-auf-der-schmelz';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery1.max-1920x1080.jpg' where slug = 'oead-apartment-hafnersteig';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery1.max-1920x1080.jpg' where slug = 'oead-apartment-obermuellnerstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Poetzleinsdorfer_Gallery-Aussen.max-1920x1080.jpg' where slug = 'oead-apartment-poetzleinsdorfer-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery2.max-1920x1080.jpg' where slug = 'popup-dorms';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery1.max-1920x1080.jpg' where slug = 'sonnenallee';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery1.max-1920x1080.jpg' where slug = 'adelheid-popp-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery1.max-1920x1080.jpg' where slug = 'brigittenauer-laende';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-DonaufeldStraße.jpg' where slug = 'donaufelderstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Gallery_2.max-1920x1080.jpg' where slug = 'dueckegasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery1.max-1920x1080.jpg' where slug = 'forsthausgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/garnisongasse_gallery1.max-1920x1080.jpg' where slug = 'garnisongasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_gallery1.max-1920x1080.jpg' where slug = 'gumpendorferstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gymnasiumstrasse_gallery1.max-1920x1080.jpg' where slug = 'gymnasiumstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/josefbaumanngasse_gallery13.max-1920x1080.jpg' where slug = 'josef-baumann-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery3.max-1920x1080.jpg' where slug = 'kaisermuehlenstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Gallery_1.max-1920x1080.jpg' where slug = 'lorenz-mueller-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery1.max-1920x1080.jpg' where slug = 'medwedweg';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery1.max-1920x1080.jpg' where slug = 'peter-jordan-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery1.max-1920x1080.jpg' where slug = 'tuerkenstrasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2021/08/STUWO-Arsenal-Aussenansicht.jpg' where slug = 'stuwo-arsenal';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Seestadt-Aspern.jpg' where slug = 'stuwo-seestadt-aspern';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Dueckegasse.jpg' where slug = 'stuwo-dueckegasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Triesterstraße.jpg' where slug = 'stuwo-triester-strasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Kenyongasse.jpg' where slug = 'stuwo-kenyongasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Strozzigasse.jpg' where slug = 'stuwo-strozzigasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Strudlhofgasse.jpg' where slug = 'stuwo-strudlhofgasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Simmering.jpg' where slug = 'stuwo-simmering';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Spengergasse.jpg' where slug = 'stuwo-spengergasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Vorgartenstraße.jpg' where slug = 'stuwo-vorgartenstrasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-Auf-der-Schmelz.jpg' where slug = 'stuwo-schmelz';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/04/Wien-DonaufeldStraße.jpg' where slug = 'stuwo-donaufelder-strasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2021/11/home4students_Grosse_Schiffgasse_aussen_1_conrete-web.jpg' where slug = 'h4s-grosse-schiffgasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2026/01/home4students-Schaeffergasse-Aussenansicht-e1767786075976.jpg' where slug = 'h4s-schaeffergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/neudeggergasse_aussen.jpg' where slug = 'h4s-neudeggergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2024/04/home4students_Boltzmanngasse_Aussenaufnahme-e1712140495902.jpg' where slug = 'h4s-boltzmanngasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/h4s_Hoefergasse_Au·enansicht.jpg' where slug = 'h4s-hofergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/07/home4students_Sensengasse_Außenaufnahme.jpg' where slug = 'h4s-sensengasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/home4students-Erlachplatz-Aussenansicht.jpg' where slug = 'h4s-erlachplatz';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2024/12/DWP_4981-scaled.jpg' where slug = 'h4s-ullmannstrasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/h4s_Doebling2_Außenansicht2.jpg' where slug = 'h4s-doebling-front';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/h4s_Doebling2_Außenansicht2.jpg' where slug = 'h4s-doebling-back';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/home4students_popupdorms_aussenbereich.jpg' where slug = 'h4s-popup-seestadt';
