-- ============================================================================
-- Seed: dorm hero images (generated by scripts/fetch-dorm-images.mjs)
-- APPLY: psql $DATABASE_URL -f supabase/seeds/dorm_images.sql
-- Idempotent: upserts image_url on slug.
-- ============================================================================

update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Gasgasse.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-gasgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-kandlgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-molkereistrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-sechshauser-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-simmeringer-hauptstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tigergasse_header2.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-guesthouse-tigergasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/AufDerSchmelz_Header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-apartment-auf-der-schmelz';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-apartment-hafnersteig';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_header.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-apartment-obermuellnerstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Poetzleinsdorfer_Header.Neujpg.2e16d0ba.fill-1580x240.jpg' where slug = 'oead-apartment-poetzleinsdorfer-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_header.2e16d0ba.fill-1580x240.jpg' where slug = 'popup-dorms';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_header.2e16d0ba.fill-1580x240.jpg' where slug = 'sonnenallee';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_header.2e16d0ba.fill-1580x240.jpg' where slug = 'adelheid-popp-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_header.2e16d0ba.fill-1580x240.jpg' where slug = 'brigittenauer-laende';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Donaufelder_Header.2e16d0ba.fill-1580x240.jpg' where slug = 'donaufelderstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Header1.2e16d0ba.fill-1580x240.jpg' where slug = 'dueckegasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'forsthausgasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/garnisongasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'garnisongasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'gumpendorferstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gymnasiumstrasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'gymnasiumstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/J_Baumann_HeaderWeb.2e16d0ba.fill-1580x240.jpg' where slug = 'josef-baumann-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'kaisermuehlenstrasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Header.2e16d0ba.fill-1580x240.jpg' where slug = 'lorenz-mueller-gasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_header.2e16d0ba.fill-1580x240.jpg' where slug = 'medwedweg';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_header.2e16d0ba.fill-1580x240.jpg' where slug = 'peter-jordan-strasse';
update public.dorms set image_url = 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_header.2e16d0ba.fill-1580x240.jpg' where slug = 'tuerkenstrasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2021/03/STUWO-Arsenal-Zimmer-mit-Terrasse-Kategorie-B2.jpg' where slug = 'stuwo-arsenal';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2020/10/STUWO-Seestadt-Aspern-See.jpg' where slug = 'stuwo-seestadt-aspern';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2021/11/H9_Balkon_1-e1567510253141.jpg' where slug = 'stuwo-dueckegasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/07/H21_Studierraum_7.jpg' where slug = 'stuwo-triester-strasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/06/H4_Gemeinschaftsküche_11-1.jpg' where slug = 'stuwo-kenyongasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2023/09/STUWO-Strozzigasse-Kleinkueche-Kategorie-A-und-D-1.jpg' where slug = 'stuwo-strozzigasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/09/community_wien_4-1030x687.jpg' where slug = 'stuwo-strudlhofgasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/07/H7_Gemeinschaftsraum_2.jpg' where slug = 'stuwo-simmering';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/06/H6_Balkon_3.jpg' where slug = 'stuwo-spengergasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/06/1_H10_Zimmer_Kat.B_2.jpg' where slug = 'stuwo-vorgartenstrasse';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/07/H13_Terasse_2.jpg' where slug = 'stuwo-schmelz';
update public.dorms set image_url = 'https://www.stuwo.at/wp-content/uploads/2019/07/H12_Zimmer_Kat.A_11.jpg' where slug = 'stuwo-donaufelder-strasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2021/11/home4students_Grosse_Schiffgasse_aussen_1_conrete-web.jpg' where slug = 'h4s-grosse-schiffgasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2023/02/Kaiserschild_Walls_of_Vision_Neuinterpretation_2__c_Franziska_Liehl-scaled.jpg' where slug = 'h4s-schaeffergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/neudeggergasse_aussen.jpg' where slug = 'h4s-neudeggergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/home4students_Boltzmanngasse_Au·enaufnahme.jpg' where slug = 'h4s-boltzmanngasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/h4s_Hoefergasse_Au·enansicht.jpg' where slug = 'h4s-hofergasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/07/home4students_Sensengasse_Außenaufnahme.jpg' where slug = 'h4s-sensengasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/home4students-Erlachplatz-Aussenansicht.jpg' where slug = 'h4s-erlachplatz';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2026/01/Home4students-Ullmannstrasse-Ansicht-scaled-e1769072174498.png' where slug = 'h4s-ullmannstrasse';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2024/09/20240829_142706-768x1024.jpg' where slug = 'h4s-doebling-front';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/h4s_Doebling2_Au·enansicht2.jpg' where slug = 'h4s-doebling-back';
update public.dorms set image_url = 'https://www.home4students.at/wp-content/uploads/2019/02/home4students_popupdorms_aussenbereich.jpg' where slug = 'h4s-popup-seestadt';
