-- ============================================================================
-- Seed: OeAD dorm photo galleries (generated by scripts/fetch-dorm-galleries.mjs)
-- Additive to dorm_images.sql (dorms.image_url single hero) — populates the
-- dorm_images table used by the detail-page gallery carousel.
-- APPLY: psql $DATABASE_URL -f supabase/seeds/dorm_image_galleries.sql
-- Idempotent: ON CONFLICT (dorm_id, url) DO NOTHING.
-- ============================================================================

-- oead-guesthouse-gasgasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-gasgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery3.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-gasgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery5.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-gasgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery4.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-guesthouse-gasgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gasgasse_gallery2.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-guesthouse-gasgasse'
  on conflict (dorm_id, url) do nothing;

-- oead-guesthouse-kandlgasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-kandlgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery6.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-kandlgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery2.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-kandlgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery4.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-guesthouse-kandlgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kandlgasse_gallery7.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-guesthouse-kandlgasse'
  on conflict (dorm_id, url) do nothing;

-- oead-guesthouse-molkereistrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-molkereistrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery8.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-molkereistrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery3.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-molkereistrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery2.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-guesthouse-molkereistrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/molkereistrasse_gallery7.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-guesthouse-molkereistrasse'
  on conflict (dorm_id, url) do nothing;

-- oead-guesthouse-sechshauser-strasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-sechshauser-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery8.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-sechshauser-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery2.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-sechshauser-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery10.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-guesthouse-sechshauser-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sechshauser_gallery9.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-guesthouse-sechshauser-strasse'
  on conflict (dorm_id, url) do nothing;

-- oead-guesthouse-simmeringer-hauptstrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-simmeringer-hauptstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery6.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-simmeringer-hauptstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery3.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-simmeringer-hauptstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery11.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-guesthouse-simmeringer-hauptstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/simmering_gallery10.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-guesthouse-simmeringer-hauptstrasse'
  on conflict (dorm_id, url) do nothing;

-- oead-guesthouse-tigergasse (3 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tigergasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-guesthouse-tigergasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tigergasse_gallery2.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-guesthouse-tigergasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Tigergasse_Gallery_1.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-guesthouse-tigergasse'
  on conflict (dorm_id, url) do nothing;

-- oead-apartment-auf-der-schmelz (2 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/AufDerSchmelz_Gallery-Eingang.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-apartment-auf-der-schmelz'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/AufDerSchmelz_Gallery-Terasse2.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-apartment-auf-der-schmelz'
  on conflict (dorm_id, url) do nothing;

-- oead-apartment-hafnersteig (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-apartment-hafnersteig'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery3.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-apartment-hafnersteig'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery2.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-apartment-hafnersteig'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery5.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-apartment-hafnersteig'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/hafnersteig_gallery6.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-apartment-hafnersteig'
  on conflict (dorm_id, url) do nothing;

-- oead-apartment-obermuellnerstrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-apartment-obermuellnerstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery3.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-apartment-obermuellnerstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery7.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-apartment-obermuellnerstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery6.max-1920x1080.jpg', 3 from public.dorms where slug = 'oead-apartment-obermuellnerstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/obermuellner_gallery2.max-1920x1080.jpg', 4 from public.dorms where slug = 'oead-apartment-obermuellnerstrasse'
  on conflict (dorm_id, url) do nothing;

-- oead-apartment-poetzleinsdorfer-strasse (3 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Poetzleinsdorfer_Gallery-Aussen.max-1920x1080.jpg', 0 from public.dorms where slug = 'oead-apartment-poetzleinsdorfer-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Poetzleinsdorfer_Gallery-Aussen3.max-1920x1080.jpg', 1 from public.dorms where slug = 'oead-apartment-poetzleinsdorfer-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Poetzleinsdorfer_Gallery-Aussen2.max-1920x1080.jpg', 2 from public.dorms where slug = 'oead-apartment-poetzleinsdorfer-strasse'
  on conflict (dorm_id, url) do nothing;

-- popup-dorms (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery2.max-1920x1080.jpg', 0 from public.dorms where slug = 'popup-dorms'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery7.max-1920x1080.jpg', 1 from public.dorms where slug = 'popup-dorms'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery12.max-1920x1080.jpg', 2 from public.dorms where slug = 'popup-dorms'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery10.max-1920x1080.jpg', 3 from public.dorms where slug = 'popup-dorms'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/popupdorms_gallery1.max-1920x1080.jpg', 4 from public.dorms where slug = 'popup-dorms'
  on conflict (dorm_id, url) do nothing;

-- sonnenallee (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'sonnenallee'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery7.max-1920x1080.jpg', 1 from public.dorms where slug = 'sonnenallee'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery6.max-1920x1080.jpg', 2 from public.dorms where slug = 'sonnenallee'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery5.max-1920x1080.jpg', 3 from public.dorms where slug = 'sonnenallee'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/sonnenallee_gallery16.max-1920x1080.jpg', 4 from public.dorms where slug = 'sonnenallee'
  on conflict (dorm_id, url) do nothing;

-- adelheid-popp-gasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'adelheid-popp-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery14.max-1920x1080.jpg', 1 from public.dorms where slug = 'adelheid-popp-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery15.max-1920x1080.jpg', 2 from public.dorms where slug = 'adelheid-popp-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery9.max-1920x1080.jpg', 3 from public.dorms where slug = 'adelheid-popp-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/adelheid-popp_gallery3.max-1920x1080.jpg', 4 from public.dorms where slug = 'adelheid-popp-gasse'
  on conflict (dorm_id, url) do nothing;

-- brigittenauer-laende (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'brigittenauer-laende'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery14.max-1920x1080.jpg', 1 from public.dorms where slug = 'brigittenauer-laende'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery7.max-1920x1080.jpg', 2 from public.dorms where slug = 'brigittenauer-laende'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery12.max-1920x1080.jpg', 3 from public.dorms where slug = 'brigittenauer-laende'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery4.max-1920x1080.jpg', 4 from public.dorms where slug = 'brigittenauer-laende'
  on conflict (dorm_id, url) do nothing;

-- dueckegasse (4 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Gallery_2.max-1920x1080.jpg', 0 from public.dorms where slug = 'dueckegasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Gallery_4.max-1920x1080.jpg', 1 from public.dorms where slug = 'dueckegasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Gallery_3.max-1920x1080.jpg', 2 from public.dorms where slug = 'dueckegasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Dueckegasse_Gallery_1.max-1920x1080.jpg', 3 from public.dorms where slug = 'dueckegasse'
  on conflict (dorm_id, url) do nothing;

-- forsthausgasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'forsthausgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery10.max-1920x1080.jpg', 1 from public.dorms where slug = 'forsthausgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery11.max-1920x1080.jpg', 2 from public.dorms where slug = 'forsthausgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery12.max-1920x1080.jpg', 3 from public.dorms where slug = 'forsthausgasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/forsthausgasse_gallery4.max-1920x1080.jpg', 4 from public.dorms where slug = 'forsthausgasse'
  on conflict (dorm_id, url) do nothing;

-- garnisongasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/garnisongasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'garnisongasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Garnisonsgasse_Gallery_5.max-1920x1080.jpg', 1 from public.dorms where slug = 'garnisongasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Garnisonsgasse_Gallery_1.max-1920x1080.jpg', 2 from public.dorms where slug = 'garnisongasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Garnisonsgasse_Gallery_7.max-1920x1080.jpg', 3 from public.dorms where slug = 'garnisongasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Garnisonsgasse_Gallery_3.max-1920x1080.jpg', 4 from public.dorms where slug = 'garnisongasse'
  on conflict (dorm_id, url) do nothing;

-- gumpendorferstrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'gumpendorferstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_gallery6.max-1920x1080.jpg', 1 from public.dorms where slug = 'gumpendorferstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_gallery4.max-1920x1080.jpg', 2 from public.dorms where slug = 'gumpendorferstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/gumpendorferstrasse_gallery8.max-1920x1080.jpg', 3 from public.dorms where slug = 'gumpendorferstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/Gumpendorfer-Gallery_1.max-1920x1080.jpg', 4 from public.dorms where slug = 'gumpendorferstrasse'
  on conflict (dorm_id, url) do nothing;

-- josef-baumann-gasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/josefbaumanngasse_gallery13.max-1920x1080.jpg', 0 from public.dorms where slug = 'josef-baumann-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/josefbaumanngasse_gallery3.max-1920x1080.jpg', 1 from public.dorms where slug = 'josef-baumann-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/josefbaumanngasse_gallery8.max-1920x1080.jpg', 2 from public.dorms where slug = 'josef-baumann-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/J_BaumannGallery1.max-1920x1080.jpg', 3 from public.dorms where slug = 'josef-baumann-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/josefbaumanngasse_gallery2.max-1920x1080.jpg', 4 from public.dorms where slug = 'josef-baumann-gasse'
  on conflict (dorm_id, url) do nothing;

-- kaisermuehlenstrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery3.max-1920x1080.jpg', 0 from public.dorms where slug = 'kaisermuehlenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery12.max-1920x1080.jpg', 1 from public.dorms where slug = 'kaisermuehlenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery8.max-1920x1080.jpg', 2 from public.dorms where slug = 'kaisermuehlenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery6.max-1920x1080.jpg', 3 from public.dorms where slug = 'kaisermuehlenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/kaisermuehlenstrasse_gallery10.max-1920x1080.jpg', 4 from public.dorms where slug = 'kaisermuehlenstrasse'
  on conflict (dorm_id, url) do nothing;

-- lorenz-mueller-gasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Gallery_1.max-1920x1080.jpg', 0 from public.dorms where slug = 'lorenz-mueller-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Gallery_2.max-1920x1080.jpg', 1 from public.dorms where slug = 'lorenz-mueller-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/brigittenauer_laende_gallery9.max-1920x1080.jpg', 2 from public.dorms where slug = 'lorenz-mueller-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Gallery_Billard.max-1920x1080.jpg', 3 from public.dorms where slug = 'lorenz-mueller-gasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/LorenzMuellerGasse_Gallery_Gemeinschaftsra.max-1920x1080.jpg', 4 from public.dorms where slug = 'lorenz-mueller-gasse'
  on conflict (dorm_id, url) do nothing;

-- medwedweg (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'medwedweg'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery2.max-1920x1080.jpg', 1 from public.dorms where slug = 'medwedweg'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery5.max-1920x1080.jpg', 2 from public.dorms where slug = 'medwedweg'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery6.max-1920x1080.jpg', 3 from public.dorms where slug = 'medwedweg'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/medwedweg_gallery8.max-1920x1080.jpg', 4 from public.dorms where slug = 'medwedweg'
  on conflict (dorm_id, url) do nothing;

-- peter-jordan-strasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'peter-jordan-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery2.max-1920x1080.jpg', 1 from public.dorms where slug = 'peter-jordan-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery6.max-1920x1080.jpg', 2 from public.dorms where slug = 'peter-jordan-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery7.max-1920x1080.jpg', 3 from public.dorms where slug = 'peter-jordan-strasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/peter_jordan_gallery3.max-1920x1080.jpg', 4 from public.dorms where slug = 'peter-jordan-strasse'
  on conflict (dorm_id, url) do nothing;

-- tuerkenstrasse (5 photos)
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery1.max-1920x1080.jpg', 0 from public.dorms where slug = 'tuerkenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery5.max-1920x1080.jpg', 1 from public.dorms where slug = 'tuerkenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery11.max-1920x1080.jpg', 2 from public.dorms where slug = 'tuerkenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery3.max-1920x1080.jpg', 3 from public.dorms where slug = 'tuerkenstrasse'
  on conflict (dorm_id, url) do nothing;
insert into public.dorm_images (dorm_id, url, sort_order)
  select id, 'https://oeadstudenthousing-public-production.s3.amazonaws.com/images/tuerkenstrasse_gallery2.max-1920x1080.jpg', 4 from public.dorms where slug = 'tuerkenstrasse'
  on conflict (dorm_id, url) do nothing;
