-- ============================================================================
-- Seed: OeAD student housing — Vienna (26 residences)
-- ============================================================================
-- SOURCE: https://www.oeadstudenthousing.at/en/accommodation/vienna/
--         Metadata extracted 2026-07-02 (name, path, min monthly price)
--
-- APPLY (Supabase SQL editor or CLI):
--   psql $DATABASE_URL -f supabase/seeds/oead_vienna.sql
--
-- REQUIRES: public.dorms table with unique slug column.
-- PREREQUISITE for cron: merge PR #5 (OeAD Playwright scraper) + set env vars.
--
-- Idempotent: safe to re-run (upserts on slug).
-- ============================================================================

insert into public.dorms (
  slug,
  provider,
  name,
  address,
  district,
  price_min,
  website_url,
  apply_url,
  scrape_url,
  scrape_type,
  active
)
values
  ('oead-guesthouse-gasgasse', 'OeAD', 'Gasgasse', 'Gasgasse 2, 1150 Wien', 15, 723,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-gasgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-gasgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-gasgasse/', 'playwright', true),
  ('oead-guesthouse-kandlgasse', 'OeAD', 'Kandlgasse', 'Kandlgasse 30, 1070 Wien', 7, 676,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-kandlgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-kandlgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-kandlgasse/', 'playwright', true),
  ('oead-guesthouse-molkereistrasse', 'OeAD', 'Molkereistrasse', 'Molkereistrasse 1, 1020 Wien', 2, 666,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-molkereistrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-molkereistrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-molkereistrasse/', 'playwright', true),
  ('oead-guesthouse-sechshauser-strasse', 'OeAD', 'Sechshauser Strasse', 'Sechshauser Strasse 31, 1150 Wien', 15, 446,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-sechshauser-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-sechshauser-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-sechshauser-strasse/', 'playwright', true),
  ('oead-guesthouse-simmeringer-hauptstrasse', 'OeAD', 'Simmeringer Hauptstrasse', 'Simmeringer Hauptstrasse 143, 1110 Wien', 11, 603,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-simmeringer-hauptstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-simmeringer-hauptstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-simmeringer-hauptstrasse/', 'playwright', true),
  ('oead-guesthouse-tigergasse', 'OeAD', 'Tigergasse', 'Tigergasse 23-27, 1080 Wien', 8, 446,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-tigergasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-tigergasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-guesthouse-tigergasse/', 'playwright', true),
  ('oead-apartment-auf-der-schmelz', 'OeAD', 'Auf der Schmelz', 'Auf der Schmelz 10, 1150 Wien', 15, 666,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-auf-der-schmelz/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-auf-der-schmelz/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-auf-der-schmelz/', 'playwright', true),
  ('oead-apartment-hafnersteig', 'OeAD', 'Hafnersteig', 'Hafnersteig 5, 1010 Wien', 1, 1290,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-hafnersteig/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-hafnersteig/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-hafnersteig/', 'playwright', true),
  ('oead-apartment-obermuellnerstrasse', 'OeAD', 'Obermuellnerstrasse', 'Obermuellnerstrasse 2c, 1020 Wien', 2, 437,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-obermuellnerstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-obermuellnerstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-obermuellnerstrasse/', 'playwright', true),
  ('oead-apartment-poetzleinsdorfer-strasse', 'OeAD', 'Poetzleinsdorfer Strasse', 'Poetzleinsdorfer Strasse 38, 1180 Wien', 18, 978,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-poetzleinsdorfer-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-poetzleinsdorfer-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/oead-apartment-poetzleinsdorfer-strasse/', 'playwright', true),
  ('popup-dorms', 'OeAD', 'PopUp dorms', 'Sonnenallee 105, 1220 Wien', 22, 439,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/popup-dorms/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/popup-dorms/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/popup-dorms/', 'playwright', true),
  ('sonnenallee', 'OeAD', 'Sonnenallee', 'Sonnenallee 41, 1220 Wien', 22, 416,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/sonnenallee/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/sonnenallee/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/sonnenallee/', 'playwright', true),
  ('adelheid-popp-gasse', 'OeAD', 'Adelheid-Popp-Gasse', 'Adelheid-Popp-Gasse 24, 1220 Wien', 22, 638,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/adelheid-popp-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/adelheid-popp-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/adelheid-popp-gasse/', 'playwright', true),
  ('brigittenauer-laende', 'OeAD', 'Brigittenauer Laende', 'Brigittenauer Laende 224, 1200 Wien', 20, 372,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/brigittenauer-laende/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/brigittenauer-laende/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/brigittenauer-laende/', 'playwright', true),
  ('donaufelderstrasse', 'OeAD', 'Donaufelder Strasse', 'Donaufelder Strasse 54, 1210 Wien', 21, 560,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/donaufelderstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/donaufelderstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/donaufelderstrasse/', 'playwright', true),
  ('dueckegasse', 'OeAD', 'Dueckegasse', 'Dueckegasse 3, 1220 Wien', 22, 620,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/dueckegasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/dueckegasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/dueckegasse/', 'playwright', true),
  ('forsthausgasse', 'OeAD', 'Forsthausgasse', 'Forsthausgasse 2-8, 1200 Wien', 20, 459,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/forsthausgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/forsthausgasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/forsthausgasse/', 'playwright', true),
  ('garnisongasse', 'OeAD', 'Garnisongasse', 'Garnisongasse 14-16, 1090 Wien', 9, 493,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/garnisongasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/garnisongasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/garnisongasse/', 'playwright', true),
  ('gumpendorferstrasse', 'OeAD', 'Gumpendorferstrasse', 'Gumpendorferstrasse 39, 1060 Wien', 6, 340,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gumpendorferstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gumpendorferstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gumpendorferstrasse/', 'playwright', true),
  ('gymnasiumstrasse', 'OeAD', 'Gymnasiumstrasse', 'Gymnasiumstrasse 85, 1190 Wien', 19, 539,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gymnasiumstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gymnasiumstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/gymnasiumstrasse/', 'playwright', true),
  ('josef-baumann-gasse', 'OeAD', 'Josef-Baumann-Gasse', 'Josef-Baumann-Gasse 8a, 1220 Wien', 22, 551,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/josef-baumann-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/josef-baumann-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/josef-baumann-gasse/', 'playwright', true),
  ('kaisermuehlenstrasse', 'OeAD', 'Kaisermuehlenstrasse', 'Kaisermuehlenstrasse 14, 1220 Wien', 22, 657,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/kaisermuehlenstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/kaisermuehlenstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/kaisermuehlenstrasse/', 'playwright', true),
  ('lorenz-mueller-gasse', 'OeAD', 'Lorenz-Mueller-Gasse 1A', 'Lorenz-Mueller-Gasse 1A, 1200 Wien', 20, 459,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/lorenz-mueller-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/lorenz-mueller-gasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/lorenz-mueller-gasse/', 'playwright', true),
  ('medwedweg', 'OeAD', 'Medwedweg', 'Medwedweg 3, 1110 Wien', 11, 644,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/medwedweg/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/medwedweg/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/medwedweg/', 'playwright', true),
  ('peter-jordan-strasse', 'OeAD', 'Peter-Jordan-Strasse', 'Peter-Jordan-Strasse 1, 1190 Wien', 19, 628,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/peter-jordan-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/peter-jordan-strasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/peter-jordan-strasse/', 'playwright', true),
  ('tuerkenstrasse', 'OeAD', 'Tuerkenstrasse', 'Tuerkenstrasse 3, 1090 Wien', 9, 449,
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/tuerkenstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/tuerkenstrasse/',
   'https://www.oeadstudenthousing.at/en/accommodation/vienna/tuerkenstrasse/', 'playwright', true)
on conflict (slug) do update set
  provider    = excluded.provider,
  name        = excluded.name,
  address     = excluded.address,
  district    = excluded.district,
  price_min   = excluded.price_min,
  website_url = excluded.website_url,
  apply_url   = excluded.apply_url,
  scrape_url  = excluded.scrape_url,
  scrape_type = excluded.scrape_type,
  active      = excluded.active;